## This workflow runs Vale on the main branch and reports the results to GitHub Code Scanning so that all the "suggestion" and "warning" that are skipped can be monitored.

name: Vale reporting checks
on:
  push:
    branches:
      - main
    paths:
      - "docs/**/*.md"

jobs:
  vale-main:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run Vale (SARIF output)
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: docs/**/*.md
          output: SARIF
          no_exit: true   # don't fail if only warnings/suggestions

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vale.sarif
