name: Vale Lint

on:
  pull_request:
    paths:
      - "docs/**/*.md"

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Vale
        run: |
          VERSION=$(curl -s https://api.github.com/repos/errata-ai/vale/releases/latest | jq -r .tag_name)
          curl -fsSL "https://github.com/errata-ai/vale/releases/download/${VERSION}/vale_${VERSION#v}_Linux_64-bit.tar.gz" \
          | tar -xz -C /usr/local/bin

      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh \
          | sh -s -- -b /usr/local/bin

      - name: Run Vale with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VALE_MIN_ALERT_LEVEL=warning \
          vale --no-exit --output=line docs \
            | reviewdog -efm="%f:%l:%c: %m" \
                -name="Vale" \
                -reporter=github-pr-annotations \
                -filter-mode=file \
                -fail-on-error=false

